spring.datasource.url=jdbc:postgresql://localhost:5433/RealtimeWeatherApp
spring.datasource.username=postgres
spring.datasource.password=Nikolas
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
openweathermap.apikey=84740da919611a1e361ba4ebbf242bd0